### ISSUE TITLE
Feature suggestion: add customer group

### ISSUE THREAD

**Issue by jcgdjob** [Brille24/SyliusTierpricePlugin#27]
It would be nice if the tier price base on customer group.

**Comment by mamazu** [comment]
Thanks for using our plugin and submitting a feature suggestion. It would be a nice feature. We do not intend to add it as we don't see the business value (for us) but if you have an idea on how to implement it feel free to submit a merge request. I would be glad to help.

**Comment by jcgdjob** [comment]
I tried to override the entity but error throw:
`Fatal error: Cannot declare class App\Entity\TierPrice because the name is already in use`

```
App\Entity\TierPrice:
    type: mappedSuperclass
    table: brille24_tierprice
```

Tired also updating the resource:

```
sylius_resource:
    resources:
      brille24.tierprice:
        classes:
           model: App\Entity\TierPrice
```

Any idea?
